# Generated by Django 5.0.2 on 2024-03-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='profiles/images'),
        ),
    ]
